### ISSUE TITLE
Issue on page /appendices/appendix_a/extra_tools.html

### ISSUE THREAD

**Issue by haoxin-li** [cis-projects/project_based_course_notes#11]
Hi Luke, would you mind helping me to add three tools for Modelling Tools (I think they are not in the course notes?  Let me know if they exist already):

Lucidchart https://www.lucidchart.com/pages/
Draw.io https://www.draw.io/
Astah (free license for students) https://astah.net/

**Comment by lukearosa** [comment]
I've added it to motivational modelling section of chapter 8
