### ISSUE TITLE
Issue on page /chapter_2/client_communications.html

### ISSUE THREAD

**Issue by GrantUpson** [cis-projects/project_based_course_notes#19]
At the conclusion of a client meeting, the Minute Taker should email the client with the minutes they wrote. You don’t need to send the entire copy of notes (which can take a long time for your client to read). You could write down the main points in the meeting notes. Doing so will allow the client to correct **and** mistakes and makes sure the team does not waste time on work that is incorrect.

And should be replaced with any in the part "Doing so will allow the client to correct and mistakes and make sure the team does not waste time on work that is incorrect".

**Comment by lukearosa** [comment]
Thanks @GrantUpson!
